# Prometheus Configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:8000"]
    metrics_path: "/metrics"

  - job_name: "auth-service"
    static_configs:
      - targets: ["auth-service:8003"]
    metrics_path: "/metrics"

  - job_name: "clinic-service"
    static_configs:
      - targets: ["clinic-service:8001"]
    metrics_path: "/metrics"

  - job_name: "booking-service"
    static_configs:
      - targets: ["booking-service:8002"]
    metrics_path: "/metrics"

  - job_name: "review-service"
    static_configs:
      - targets: ["review-service:8004"]
    metrics_path: "/metrics"

  - job_name: "notification-service"
    static_configs:
      - targets: ["notification-service:8005"]
    metrics_path: "/metrics"

  - job_name: "data-collector-service"
    static_configs:
      - targets: ["data-collector-service:8006"]
    metrics_path: "/metrics"
